language: node_js
matrix:
  include:
  - os: osx
    node_js: '4'
    osx_image: xcode7.3
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
    sudo: required
    dist: trusty
    node_js: '4'
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
addons:
  apt:
    packages:
    - icnsutils
    - graphicsmagick
    - xz-utils
before_install:
- npm install -g eslint eslint-config-airbnb
install:
- npm install
after_success:
- npm run dist:$TRAVIS_OS_NAME
env:
  global:
    secure: kJsMm4AoDuT47fbxohEYyZMDQEQYSQkeCsxKNZHZTn5MUZvrdryEUkFFBnrWTcnmsROueexXDwyF0DPUPxs5vnLgnQgQxNcfSrING8plM9ciN904YvVQZGN/UH/MlIo0CpsaRrEvB+rGThG0X4QOd3tXOoM1rkedbrRigVLN6VPD+Rseo35y1HVyzQ4kA77ccmOiZnXX6o/ZVPiRIHvCu3zlDiwrTtwoD848Rd36534cX1/Qk7J5D0sn7aTpHz/kr5BoTGpMFHlPmz40MFtHJFIBBeT8kb3SlgSEwrOmx+XRHdiFTOX1xGzyoP6HEyxzRIwCJetHz50ls3IMWeL0ilPz4JqwqZTJS5VKl2QdOYowRUJlNWjh5weprCQZiMszZ7usJ1YwA05+DJ/dgQWzjcEOhJV3Vsz+Q3HgCvKAQhupWckE2ibklYe582cNV9EqHGAqHROg+bmyMzce1gLMkfAmnRv7SAYcH4hIM+HYrMgjV0gvBOyGg12hoMfeS9e2KOEcEkp8u6NF+i5rFGH9/8R9beQhLrA92EgykQrhNx/2YQeE4KP7GJhGcxatUqbkFr3VaVrRkP1wWctHDinRu3JxWJYIwF9E3veXwyMKkiztdyOCq+qlHWY3XA7OsPGa3RvQyW63bBCH30E6mf0W3197+755vSuKZqHHVVdGNSQ=
deploy:
  provider: releases
  api_key:
    secure: lUfF7pzGEYT9Mo99gXN1Zhq6b0Qd+dY9Gl+D+ko8SbhMyJLvwRXjl/R9G8Ph7HSHTcmQew+n9P8gIO9kVoaGrZTQmkD5itBGryi5KmLdDChugpYNUkQv0CaacAyJz0vW4Om/ALsPjXfF7MEGER5v/4OPbAk0eMMeswTtyQE01RCIyGx4jlAV3B87S5FSiQafFFhwojdEyHtIenf4H2udt3UOgWFoI1Dk+g9tNwOhN+CTjBSjQRA8SiujPfRekLFnIGDlPaN2b8kwi1M9WeCi1j4hbWesvyNxssSB7myxsJyF25WhAPjsN2IPZcPHZNZmg2Q4acqJzHMNBJZTtqsgL/wlFoVob0QwPAH09EAnmO1MEdcAfv06Dw6I14jusT6rp7xyiKbPRjEnez0lOexbocmQzWGPJsmNGzUBmdxc9IIoMdnkzR4kM+fZXgDOZNJ0c8eN6OTcIab2fFOaDqALtXwpQTdJ+r0L6WiD0lP045VupYTazyPZf4a3tjGhuASgRArP7Dnk1j+ZsuE17hyeMYaH/p0alzogS6pt6kSA0p5bzq2yAyFc/9/OnPkoNCxqZ5pHhzeOve+a8AZQJpI+kVG/LWbc8OxbSYa+o+YbEtwzYieL7tdLqeTVX/+ajgrdfEpKSvmoK9YC+Ij2MRRQEZoe74I/ltsHHOvvHD/nc3A=
  file:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "/Users/travis/build/rafajaques/php-assistant/dist/osx/PHP Assistant-0.0.6.dmg"; fi
  on:
    repo: rafajaques/php-assistant
