osx_image: xcode7.3

sudo: required
dist: trusty

language: node_js

matrix:
  include:
    - os: osx
      node_js: "4"
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
      node_js: "4"

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils

before_install:
  - npm install -g eslint eslint-config-airbnb

install:
  - npm install

after_success:
  - npm run dist:$TRAVIS_OS_NAME
