osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron

node_js:
  - "4"
  - "5"

before_install:
  - npm install -g eslint eslint-config-airbnb

install:
  - npm install

after_success:
  - npm run dist:$TRAVIS_OS_NAME
